[WIP] Hash filename
cjk4wp/wordpress pull request #12
Opened 2018-07-07 15:52 UTC by ryotsun

Still thinking about unit testing.

Related #5

2018-07-07 16:27 UTC, ryotsun commented on src/wp-includes/formatting.php
> +	if ( preg_match( '/^[\\x{0000}-\\x{007F}]+$/u', $str, $match ) ) {
I'm just worried about here.
It returns `false` if text contains none-ASCII chars.
That means it will be affected to not only Japanese but also other none-ASCII chars.
Is it all right? :(

2018-07-07 16:30 UTC, ryotsun commented on src/wp-includes/formatting.php
> +	if ( preg_match( '/^[\\x{0000}-\\x{007F}]+$/u', $str, $match ) ) {
multi-byte = none ASCII chars?

2018-07-07 17:12 UTC, miya0001 requested changes

2018-07-07 17:12 UTC, miya0001 commented on src/wp-includes/formatting.php
> +	return md5( uniqid( microtime() . mt_rand(), true ) );
ランダムではなく元のファイル名に対して `md5()` するのがいいかなと思いました。
対して根拠はないのですが、`wp-multibyte-patch` がそうしているので、意図しない後方互換性のない変更を防げるかなと。

2018-07-07 17:12 UTC, miya0001 commented on src/wp-includes/formatting.php
> +	if ( preg_match( '/^[\\x{0000}-\\x{007F}]+$/u', $str, $match ) ) {
とりあえずいいと思います！

2018-07-08 03:39 UTC, ryotsun commented on src/wp-includes/formatting.php
> +	return md5( uniqid( microtime() . mt_rand(), true ) );
確かにそのほうがよさそうですねー。変更しておきました。

2018-07-08 19:47 UTC, miya0001 approved these changes

2018-07-10 05:47 UTC, miya0001 commented
すいません！閉じます！ありがとうございました！

2018-07-10 05:47 UTC, closed without merging